name: Revert pushed commit

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'main'

      release:
        description: 'enter the release'
        required: true
        default: 'Head'

jobs:
  revert_commit:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
           ref: ${{ github.event.inputs.branch }}
           fetch-depth: 0


      - name: get the release hash
        id: out-hash
        run: |
          hash=$(git show-ref --tags -s ${{ github.event.inputs.release }})
          echo $hash
          echo "release-hash=$hash" >> $GITHUB_OUTPUT
      
      
      
      - name: Revert pushed commit
        run: |
          git rev-parse HEAD
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git log --pretty=format:"%H" ${{ steps.out-hash.outputs.release-hash }}..HEAD
          git revert --no-edit -n -m 1 ${{ steps.out-hash.outputs.release-hash }}..HEAD
          git commit -m "revert to release ${{ github.event.inputs.release }})"
          #git push
